version: "2"
services:
  mysql:
    image: mysql:8.0.19
    ports:
      - "3307:3306"
    environment:
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: lcs
      MYSQL_ROOT_PASSWORD: root_password
  php:
    build: php-fpm
    ports:
      - "9010:9000"
    volumes:
      - ../project:/var/www/symfony:cached
      - ./logs/project:/var/www/symfony/var/logs:cached
    links:
      - mysql
  nginx:
    build: nginx
    ports:
      - "8081:80"
    links:
      - php
      - mysql
    volumes_from:
      - php
    volumes:
      - ./logs/nginx/:/var/log/nginx:cached
  ngrok:
    image: nginx
    volumes:
      - ../docker:/var/www/docker
    command: /var/www/docker/ngrok/ngrok http nginx:80 -config=/var/www/docker/ngrok/ngrok.conf
    links:
      - php
      - nginx
    ports:
      - 4040:4040